name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    uses: ./.github/workflows/reusable-build.yml # Reuse the build workflow
    with:
      dotnet_version: 9.0.x # Pass the .NET version dynamically into the reusable workflow