name: Reusable - Build

on:
  workflow_call:
    inputs:
      dotnet_version: # dotnet version on line 21
        required: true
        type: string

jobs:
  build:
    name: Reusable - Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }} # pass the version dynamically

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build